### ISSUE TITLE
Internal Server Error 500 - None of the configured nodes are available

### ISSUE THREAD

**Issue by Manas-Nagelia** [USDA/USDA-APIs#126]
Hello.

This afternoon when I was working with the Food Date API, I started receiving internal server errors that said:

`
{
  "status": 500,
  "error": "Internal Server Error",
  "message": "None of the configured nodes are available: [{#transport#-1}{Q_ZlAgIzSYOGfxfgoykFXg}{fdc-node1.nal.usda.gov}{199.133.202.71:9300}, {#transport#-2}{Xvy9c9y-SfmMJ_mffTeN3Q}{fdc-node2.nal.usda.gov}{199.133.202.72:9300}]"
}
`

Now I'm assuming this is an error on the APIs end, regarding Elastic Search. Also, on the FoodData Central website, the search doesn't work.

This issue also happened in the past: #101

**Comment by jericho1050** [comment]
I am also having the same problem; it seems the API server is down. I tried contacting or sending the Food Data Center the same question. I still haven't gotten any response. Maybe we have to temporarily halt our projects. lol

`  File "/workspaces/118679068/project/helpers.py", line 81, in search_food
    response.raise_for_status()  # Raise an exception if there's an HTTP error
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.nal.usda.gov/fdc/v1/foods/search?query=banana&api_key=wz0xIrmQfTqOYmpoeJlHB7UCNyLR3VyqoqUT30Bp&pageNumber=1&pageSize=6&dataType=Survey%20(FNDDS),Branded,Foundation`

**Comment by jericho1050** [comment]
I am also having the same problem; it seems the API server is down. I tried contacting or sending the Food Data Center the same question. I still haven't gotten any response. Maybe we have to temporarily halt our projects because no one is working weekends. lol

  File "/workspaces/118679068/project/helpers.py", line 81, in search_food response.raise_for_status()  # Raise an exception if there's an HTTP error ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.nal.usda.gov/fdc/v1/foods/search?query=banana&api_key=****************************&pageNumber=1&pageSize=6&dataType=Survey%20(FNDDS),Branded,Foundation

**Comment by jericho1050** [comment]
I am also having the same problem; it seems the API server is down. I tried contacting or sending the Food Data Center the same question. I still haven't gotten any response. Maybe we have to temporarily halt our projects because no one is working weekends. lol

`File "/workspaces/118679068/project/helpers.py", line 81, in search_food response.raise_for_status() # Raise an exception if there's an HTTP error ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.nal.usda.gov/fdc/v1/foods/search?query=banana&api_key=****************************&pageNumber=1&pageSize=6&dataType=Survey%20(FNDDS),Branded,Foundation`

**Comment by Manas-Nagelia** [comment]
Testing it out right now looks like it has been fixed.

**Comment by upieper** [comment]
Sorry for the inconvenience, we fixed it earlier this morning. Glad it’s working again for you! And thanks for having opened the issue.
